<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace N1215\LaraTodo\Impls\POPOAndAtlas\TodoItem;

/**
 * @property mixed $id integer NOT NULL
 * @property mixed $title varchar NOT NULL
 * @property mixed $completed_at datetime
 * @property mixed $created_at datetime
 * @property mixed $updated_at datetime
 */
trait TodoItemFields
{
}
