<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace N1215\LaraTodo\Impls\POPOAndAtlas\TodoItem;

use Atlas\Table\Row;

/**
 * @property mixed $id integer NOT NULL
 * @property mixed $title varchar NOT NULL
 * @property mixed $completed_at datetime
 * @property mixed $created_at datetime
 * @property mixed $updated_at datetime
 */
class TodoItemRow extends Row
{
    protected $cols = [
        'id' => null,
        'title' => null,
        'completed_at' => null,
        'created_at' => null,
        'updated_at' => null,
    ];
}
